# This is a basic workflow to help you get started with Actions

name: staging

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch

  pull_request:
    branches: [ staging ]
  push:
    branches: [ staging ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    env:
      ENV: ${{secrets.ENV}}
 
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      with:
        limit-access-to-actor: true
